version: "3"
services:
  node-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT = 5000
    # env_file:
    #   - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
